In [3]:
import numpy as np

a = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

sub_shape = (3,3)
view_shape = tuple(np.subtract(a.shape, sub_shape) + 1) + sub_shape
strides = a.strides + a.strides
     
sub_matrices = np.lib.stride_tricks.as_strided(a,view_shape,strides)


In [12]:
print(np.subtract(a.shape, sub_shape) + 1)

[3 3]


In [8]:
print(a.shape)

(5, 5)


In [9]:
print(view_shape)

(3, 3, 3, 3)


In [10]:
print(strides)

(40, 8, 40, 8)


In [11]:
print(sub_matrices)

[[[[ 0  1  2]
   [ 5  6  7]
   [10 11 12]]

  [[ 1  2  3]
   [ 6  7  8]
   [11 12 13]]

  [[ 2  3  4]
   [ 7  8  9]
   [12 13 14]]]


 [[[ 5  6  7]
   [10 11 12]
   [15 16 17]]

  [[ 6  7  8]
   [11 12 13]
   [16 17 18]]

  [[ 7  8  9]
   [12 13 14]
   [17 18 19]]]


 [[[10 11 12]
   [15 16 17]
   [20 21 22]]

  [[11 12 13]
   [16 17 18]
   [21 22 23]]

  [[12 13 14]
   [17 18 19]
   [22 23 24]]]]
